dist: xenial
script: bundle check
rvm:
  - 2.5.3
  - jruby-9.2.5.0
before_install:
  - gem update --system
  - gem uninstall bundler --all --ignore-dependencies --executables
  - gem install bundler --version 1.17.3
  - gem list bundler
  - bundle --version
install:
  - bundle _1.17.3_ --version
  - bundle _1.17.3_ install
before_script:
  - bundle install
